CURRENT_DIRECTORY=`dirname $(readlink ~/.zshrc)`
export ZSH="/Users/${USER}/.oh-my-zsh"
#export TERM=xterm-256color-italic

# Aliases
source $CURRENT_DIRECTORY/zsh/aliases.zsh

# Startup
source $CURRENT_DIRECTORY/zsh/startup.zsh

# Plugins
source $CURRENT_DIRECTORY/zsh/plugins.zsh

# Theme
source $CURRENT_DIRECTORY/zsh/theme.zsh

# Load extra (local) settings
[ -f ~/.zshrclocal ] && source ~/.zshrclocal

# oh-my-zsh
source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jonathangin/Desktop/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jonathangin/Desktop/google-cloud-sdk/completion.zsh.inc'; fi
eval "$(starship init zsh)"
