" Basics
set nocompatible      " We're running Vim, not Vi!
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugins
syntax on             " Enable syntax highlighting

" Custom colour scheme
set background=dark
colorscheme onedark
if (has("termguicolors"))
  set termguicolors
endif

" Tabs and spaces configuration
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab " Turns tabs into spaces
autocmd FileType html setlocal ts=2 sts=2 sw=2
autocmd FileType javascript setlocal ts=2 sts=2 sw=2
autocmd FileType json setlocal ts=2 sts=2 sw=2
autocmd FileType css setlocal ts=2 sts=2 sw=2

" UI config
set number
set showcmd

" NETRW settings
let g:netrw_liststyle = 3 " Show tree view
let g:netrw_banner = 0 " Remove useless banner
let g:netrw_winsize = 20 " Set width of explorer to 20% of page
let g:netrw_browse_split = 4
let g:netrw_altv = 1
set autochdir " Change directory to the current buffer when opening files
" augroup ProjectDrawer
"   autocmd!
"   autocmd VimEnter * :Lexplore
"   autocmd VimEnter * :wincmd p
" augroup END

" Trim whitespace on save
function! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun
autocmd BufWritePre *.rb,*.c,*.java,*.js :call <SID>StripTrailingWhitespaces()

" Spell check for markdown files
augroup markdownSpell
    autocmd!
    autocmd FileType markdown setlocal spell
    autocmd BufRead,BufNewFile *.md setlocal spell
augroup END

" Markdown Preview settings
let vim_markdown_preview_toggle=0
let vim_markdown_preview_github=1
let vim_markdown_preview_temp_file=1
let vim_markdown_preview_browser='Google Chrome'

" Custom Keymaps
" Remap esc to hh
inoremap hh <ESC>
let mapleader = "\<Space>"

" Emmet settings
let g:user_emmet_leader_key=','

" Vim Hardmode settings
let g:hardtime_default_on = 1

" Plugin manager
call plug#begin('~/.vim/plugged')
Plug 'mattn/emmet-vim'
Plug 'vim-ruby/vim-ruby'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'kaicataldo/material.vim'
Plug 'JamshedVesuna/vim-markdown-preview'
Plug 'tpope/vim-vinegar'
" Vim HardTime
Plug 'takac/vim-hardtime'
Plug 'joshdick/onedark.vim'
call plug#end()

