#ZSH_THEME="powerlevel9k/powerlevel9k"
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status context dir dir_writable vcs)
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
#POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
#POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="white"
#POWERLEVEL9K_STATUS_VERBOSE=false

ZSH_THEME=""

